### ISSUE TITLE
Public API for Market data?

### ISSUE THREAD

**Issue by aleksraiden** [phemex/phemex-api-docs#1]
Have you public endpoint for HTTP-REST - with the latest price, bid/ask and 24h total turnover (in base and currency, is can). Open Interest is important metrics too.

**Comment by phemex** [comment]
All Phemex market data is fully published by WebSocket right now, and you can find the API in our [public API page.](https://github.com/phemex/phemex-api-docs/blob/master/Public-API-en.md)

**Comment by aleksraiden** [comment]
Maybe I something dont understand. But after twise reading all docs (REST & WS) - I dont find nothing about API for instruments (symbol, assets, lot size, price tick etc.) and nothing about market snapshot - turnover 24h and Open Interest. 

May you show me, where i can find this?

**Comment by phemex** [comment]
Hi, We do not have API for contract info right now. As we will never change the definition, you can refer to https://phemex.com/web/contract/perpetual-contract?symbol=BTCUSD for contract details (eg. BTCUSD).

For 24h metrics access API, we've added it now. Please check the latest API page: https://github.com/phemex/phemex-api-docs/blob/master/Public-API-en.md.

**Comment by aleksraiden** [comment]
Lot of thanks, will start to work with him at next week. I will return ASAP as check there.

**Comment by aleksraiden** [comment]
Successful implements API, all work fine. 

So, open question - how and where obtain current funding rate (awesome - adding it to market24h packet). And, very important - fetching mark and index price.

Lot of thanks about any support!

**Comment by phemex** [comment]
All of those are not official open APIs, we may change them based on our own needs.
But you still can subscribe them like blow.

Index Price:
`
{"method":"tick.subscribe","params":[".BTC"],"id":1}
`
Mark Price:
`
{"method":"tick.subscribe","params":[".MBTC"],"id":1}
`
Realtime estimated funding rate:
`
{"method":"tick.subscribe","params":[".BTCFR"],"id":6}
`
Last settled funding rate:
`
{"method":"tick.subscribe","params":[".BTCFR8H"],"id":8}
`

**Comment by aleksraiden** [comment]
Lot of thanks, added this info.
