### ISSUE TITLE
How can I trade(order) with a sub-account(given userID) 

### ISSUE THREAD

**Issue by yilidong** [phemex/phemex-api-docs#49]
I opened several sub accounts, and each one has a userID and nickname. In each one's contract wallet, there are enough USD deposit. How can I trade in sub account(givern userID) by API?

**Comment by msolomonTMG** [comment]
I would like to know how to do this as well

**Comment by yilidong** [comment]
> I would like to know how to do this as well

Finally, I found it. Switch to login a sub account and create a new api-key inside that.

**Comment by msolomonTMG** [comment]
This worked for me too. You might want to close this issue @yilidong
