### ISSUE TITLE
TE_QTY_TOO_SMALL no idea why

### ISSUE THREAD

**Issue by jcporter** [phemex/phemex-api-docs#55]
Not sure what this even means, but when I try to place an order, I get TE_QTY_TOO_SMALL

Can't find anything anywhere.  

These are my params.  Note the price of ADA is $1.54 as of this writing and I can place this order if I manually do it on the site.

params = {
    'symbol'      : 'ADAUSD',
    'side'        : 'Buy',
    'ordType'     : 'Limit',
    'baseQtyEv'   : 100,
    'priceEp'     : 1.40
}

**Comment by msolomonTMG** [comment]
@jcporter try multiplying your baseQtyEv by 10000

**Comment by jcporter** [comment]
That fixed it.  Also, I had to transfer funds to my from my spot wallet to my contract account.  Thank you!

**Comment by msolomonTMG** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/12f3a5e1-c85f-49cd-94f4-6dce9cb18ef1-3e48e6cb-7f62-4cc7-bf9c-6bc01d2c8445-v1.png?transparent=1&palette=1&width=246) No prob. You might want to close this issue if it is no longer a problem :)
