### ISSUE TITLE
How can I get a list of all spot markets?

### ISSUE THREAD

**Issue by johnnyApplePRNG** [phemex/phemex-api-docs#61]
I am looking for an endpoint like this : https://api.phemex.com/exchange/public/products (which only lists futures)

But for your spot markets.

I can't find anything close to it on : https://github.com/phemex/phemex-api-docs/blob/master/Public-Spot-API-en.md

**Comment by phemex** [comment]
we update the API info. pls check https://github.com/phemex/phemex-api-docs/blob/master/Public-Spot-API-en.md#queryproductinfo
